name: wntt

# This is a RUN-ONLY compose.  All building is done on dev machine, and images pushed to DockerHub.

services:
    app:
        image: gordo169/wnttapp:amd
        container_name: app-c
        environment:
            NODE_ENV: production
        ports:
            # host port : container port
            - 80:80
            - 443:443
        restart: unless-stopped
        volumes:
            # keep the logs out of the container so they persist between runs.
            # This blows away the 2 sym links to /dev/stdout & /dev/stderr that the image creates.
            # The "docker logs" command will no longer show these. Use "tail -f /var/log/wntt/access.log" etc instead.
            - /var/log/wntt:/var/log/nginx
            - /etc/letsencrypt:/cert
            # Uncomment to allow quick debugging on prod
            # - ./nginx:/etc/nginx/conf.d

    api:
        image: gordo169/wnttapi:amd
        environment:
            DJANGO_SETTINGS_MODULE: project.settings.prod
            SECRET_KEY: ${DJANGO_KEY}
            CDMO_USER: ${CDMO_USER}
            CDMO_PASSWORD: ${CDMO_PASSWORD}
            API_ALLOWED_HOST: api-c
            NAVD88_MLLW_CONVERSION: ${NAVD88_MLLW_CONVERSION}
            MEAN_HIGH_WATER_MLLW: ${MEAN_HIGH_WATER_MLLW}
            RECORD_TIDE_NAVD88: ${RECORD_TIDE_NAVD88}
            RECORD_TIDE_DATE: ${RECORD_TIDE_DATE}
        container_name: api-c
        # No port publishing, container will listen on 8001, but it's only accessible by nginx in the app container
        restart: unless-stopped
        volumes:
            - /home/tides/surge/data:/surgedata
            - /var/log/wntt:/var/log/wntt
