FROM node:current-bullseye-slim

WORKDIR /app
COPY package.json package-lock.json .

RUN npm ci   # run clean install

COPY index.html eslint.config.js vite.config.js .env.development ./
ARG BUILDNUM=?
ENV VITE_BUILD_NUM=${BUILDNUM}
# This is not necessary if we're mounting the src directory in the compose file, for hot module replacement (HMR)
# COPY src ./src/
COPY public ./public/

# NOTE: if you use "npm run dev", it honors the port in vite.config.js
# but if you build (transpiles to dist/) you have to run "serve -p 3001 -s dist" b/c it
# doesn't seem to honor vite.config.js in that case.
CMD ["npm", "run", "dev"]
