# Generated by Django 6.0.2 on 2026-02-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=13, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('S', 'Station'), ('G', 'Graph')], max_length=1)),
                ('station', models.CharField(choices=[('WE', 'welinwq'), ('NC', 'nocrcwq')], max_length=2, null=True)),
                ('version', models.CharField(max_length=7)),
                ('start', models.DateField(null=True)),
                ('days', models.SmallIntegerField(null=True)),
                ('hilo', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
