# Generated by Django 6.0.2 on 2026-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='customNav',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='screenWidth',
            field=models.SmallIntegerField(null=True),
        ),
    ]
