# Generated by Django 6.0.2 on 2026-02-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_request_customnav_request_screenwidth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noaa_id', models.CharField(max_length=7)),
                ('tide_time', models.DateTimeField()),
                ('tide', models.FloatField()),
                ('surge', models.FloatField()),
                ('bias', models.FloatField(null=True)),
                ('total', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('noaa_id', 'tide_time'), name='uniq_station_time')],
            },
        ),
    ]
