# Generated by Django 6.0.2 on 2026-03-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_surge'),
    ]

    operations = [
        migrations.AddField(
            model_name='surge',
            name='cycle',
            field=models.SmallIntegerField(null=True),
        ),
    ]
