# Generated by Django 6.0.2 on 2026-03-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_surge_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='surge',
            name='calc_bias',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='SurgeBias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noaa_id', models.CharField(max_length=7)),
                ('filedate', models.DateField()),
                ('cycle', models.SmallIntegerField()),
                ('bias', models.FloatField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('noaa_id', 'filedate', 'cycle'), name='surgebias_uk1')],
            },
        ),
    ]
