# Generated by Django 6.0.2 on 2026-03-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_surge_calc_bias_surgebias'),
    ]

    operations = [
        migrations.AddField(
            model_name='surge',
            name='calc_bias2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='surgebias',
            name='bias2',
            field=models.FloatField(null=True),
        ),
    ]
