# Generated by Django 6.0.2 on 2026-03-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_surge_calc_bias2_surgebias_bias2'),
    ]

    operations = [
        migrations.AddField(
            model_name='surge',
            name='obs',
            field=models.FloatField(null=True),
        ),
    ]
