# Generated by Django 6.0.2 on 2026-03-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_surge_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='surge',
            name='calc_bias3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='surgebias',
            name='bias3',
            field=models.FloatField(null=True),
        ),
    ]
