# Generated by Django 6.0.2 on 2026-03-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_surge_calc_bias3_surgebias_bias3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surge',
            name='total',
        ),
        migrations.AddField(
            model_name='surge',
            name='surge_1day',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='surge',
            name='surge_2day',
            field=models.FloatField(null=True),
        ),
    ]
