# Generated by Django 6.0.3 on 2026-04-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_surge_total_surge_surge_1day_surge_surge_2day'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
        migrations.AlterModelTable(
            name='surge',
            table='surge',
        ),
        migrations.AlterModelTable(
            name='surgebias',
            table='surgebias',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(choices=[('WE', 'welinwq'), ('NC', 'nocrcwq')], max_length=2)),
                ('time', models.CharField(max_length=25)),
                ('temp', models.FloatField(null=True)),
                ('level', models.FloatField()),
            ],
            options={
                'db_table': 'water',
                'constraints': [models.UniqueConstraint(fields=('station', 'time'), name='water_uk1')],
            },
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(choices=[('WE', 'welinwq'), ('NC', 'nocrcwq')], max_length=2)),
                ('time', models.CharField(max_length=25)),
                ('speed', models.FloatField()),
                ('gust', models.FloatField(null=True)),
                ('dir_deg', models.SmallIntegerField()),
                ('dir_str', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'wind',
                'constraints': [models.UniqueConstraint(fields=('station', 'time'), name='wind_uk1')],
            },
        ),
    ]
