# Generated by Django 6.0.3 on 2026-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_request_table_alter_surge_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wind',
            name='dir_str',
        ),
        migrations.AlterField(
            model_name='wind',
            name='gust',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
