# Generated by Django 6.0.3 on 2026-06-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_wind_dir_str_alter_wind_gust'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroTide15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noaa_id', models.CharField(max_length=7)),
                ('time', models.CharField(max_length=25)),
                ('nav_level', models.FloatField()),
            ],
            options={
                'db_table': 'astrotide15',
                'constraints': [models.UniqueConstraint(fields=('noaa_id', 'time'), name='astrotide15_uk1')],
            },
        ),
        migrations.CreateModel(
            name='AstroTideHilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noaa_id', models.CharField(max_length=7)),
                ('time', models.CharField(max_length=25)),
                ('real_time', models.CharField(max_length=25)),
                ('nav_level', models.FloatField()),
                ('hilo', models.CharField(choices=[('H', 'High'), ('L', 'Low')], max_length=2)),
            ],
            options={
                'db_table': 'astrotidehilo',
                'constraints': [models.UniqueConstraint(fields=('noaa_id', 'time'), name='astrotideHilo_uk1')],
            },
        ),
    ]
