# Generated by Django 6.0.3 on 2026-07-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_astrotide15_astrotidehilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='clevel_nf',
            field=models.FloatField(null=True),
        ),
    ]
