# Generated by Django 6.0.3 on 2026-08-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_water_clevel_nf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water',
            old_name='temp',
            new_name='temp_f',
        ),
        migrations.RemoveField(
            model_name='water',
            name='level',
        ),
    ]
