# Generated by Django 6.0.8 on 2026-08-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_temp_water_temp_f_remove_water_level'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='surge',
            name='uniq_station_time',
        ),
        migrations.DeleteModel(
            name='Surge',
        ),
        migrations.RemoveConstraint(
            model_name='surgebias',
            name='surgebias_uk1',
        ),
        migrations.DeleteModel(
            name='SurgeBias',
        ),
    ]
