# Generated by Django 6.0.8 on 2026-09-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_surge_uniq_station_time_delete_surge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='clevel_nf',
            field=models.FloatField(),
        ),
    ]
