#!/bin/bash -e

# Configure a host
# This script is meant to be idempotent, so will not harm any host that's already setup.
# If there were any local changes, however, they could be wiped out by running this.

HOST=209.38.48.196

tar --no-xattrs -cf setup.tar config

CMD="scp setup.tar devel@${HOST}:~"
echo $CMD
$CMD

ssh devel@$HOST '
  echo removing old config dir...
  rm -rf config

  echo extracting tar file...
  tar -xf setup.tar
  rm setup.tar
  cd config

  echo installing docker-compose.yml...
  mv docker-compose.yml docker-compose-staging.yml .env ..

  echo installing bash profile...
  mv .bash_profile ..

  echo installing bin tools...
  rm ../bin/*
  mv bin/* ../bin

  echo setting up cron...
  crontab -l > cron.backup && crontab cron.txt

  echo setting up logging...
  # sudo -S to use stdin since we have no tty
  sudo -S mkdir -p /var/log/wntt /var/log/wntt-staging
  sudo chown -R devel:devel /var/log/wntt/ /var/log/wntt-staging
  chmod 750 /var/log/wntt /var/log/wntt-staging
  sudo mv wntt-logrotate /etc/logrotate.d/wntt

  echo setting up surge directories...
  cd ..
  mkdir -p surge/data surge/incoming surge/portland

  echo done...
'
